[[material]]
name = "rubber"
density = 200
E = 1.4e5
Nu = 0.2
hardening = 0
plast_clamp_lower = 0.0
plast_clamp_higher = 1.0e30

[[object]]
material = "rubber"
mesh = "rubber_duck.obj"
size = 0.4
position = [0.3, 0.4, 0.3]
velocity = [0.0, 0.0, 0.0]

[[object]]
material = "rubber"
mesh = "cube.obj"
size = 0.3
position = [0.35, 0.5, 0.35]
velocity = [0.0, 0.0, 0.0]
lifetime_begin = 2.0

