[[material]]
name = "snow"
density = 700
E = 1.4e5
Nu = 0.2
hardening = 10
plast_clamp_lower = 0.975
plast_clamp_higher = 1.0075

[[object]]
material = "snow"
mesh = "sphere.obj"
size = 0.4
position = [0.3, 0.03, 0.3]
velocity = [0.0, 0.0, 0.0]

[[object]]
material = "snow"
mesh = "sphere.obj"
size = 0.3
position = [0.35, 0.43, 0.35]
velocity = [0.0, 0.0, 0.0]

[[object]]
material = "snow"
mesh = "sphere.obj"
size = 0.2
position = [0.4, 0.75, 0.4]
velocity = [0.0, 0.0, 0.0]

[[object]]
material = "snow"
mesh = "sphere.obj"
size = 0.1
position = [0.05, 0.5, 0.46]
velocity = [7.0, 2.5, 0.0]
lifetime_begin = 0.5


